### ISSUE TITLE
Implement support for livestream

### ISSUE THREAD

**Issue by hmurari** [visionify/visionai#14]
## Motivation
Once the web-app support is implemented - next enhancement on the web-app & edge-application would be the ability to stream from the device or any running scenario to the cloud.

Use case would be something like this:
- User installs visionai
- User starts web-app using visionai start web-app
- User adds cameras and scenarios on the web-app
- User may want to test out if the RTSP or local camera is working by just clicking PLAY button on the web-app. This should somehow stream everything from the edge-device to the cloud.

## Architecture
At a high-level, I want to use rtsp-streamer application. Since it provides support for majority of different IP cameras, it would be an ideal source to build upon. 

However, after that I am not very sure how this would be implemented overall. Several questions remain:
- visionai application is a CLI application - should we start some rtsp streamer application in the background when starting? 
- How would web-app communicate with the edge-machine? Through web-sockets or redis pubsub? We implemented something similar on Azure IoTEdge - but want to keep this framework extensible to other areas as well

## Prior codebase
We have some codebase available at https://github.com/visionify/opencv-livestream 
This implements opencv based livestream to a web-app. I think some portions of this might be usable.

**Comment by hmurari** [comment]
@sumanthvisionify Can you please look into this

**Comment by sumanthvisionify** [comment]
Thi one is done on the visionai-api old approach. I think we don't need this for new approach.
