### ISSUE TITLE
Add support for checking broken links

### ISSUE THREAD

**Issue by hmurari** [visionify/visionai#28]
### Overview
There is a Github action which uses a NPM package that can check for any broken links on our website. We want to integrate support for this in our CI/CD pipeline.

### Reference
For example, [neptune-ai package](https://github.com/neptune-ai/docs/blob/master/.github/workflows/broken-link-checker.yml) has this support. We need to go through how they have implemented it and do the same changes for our documentation modules as well.

**Comment by hmurari** [comment]
@kar122 Can you please check this?

**Comment by sumanthvisionify** [comment]
@hmurari this is issue is resolved I think
