### ISSUE TITLE
grafana directory permission issue in docker-compose

### ISSUE THREAD

**Issue by sumanthvisionify** [visionify/visionai#51]
visionai-grafana | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied

# Redis grafana docker-compose file
version: '3.4'

services:
  redis:
    container_name: visionai-redis
    image: redis
    ports:
      - '6379:6379'

  grafana:
    container_name: visionai-grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./data:/var/lib/grafana
    user: "$UID:$GID"

Add user to grafana service

**Comment by sumanthvisionify** [comment]
We should add data and provisioning folders into .gitignore

**Comment by hmurari** [comment]
We do not need additional docker-compose file. Grafana is started automatically when `visionai init` command is called.

Please check and let me know if anything is broken there. Otherwise we can close this issue.
